version: '3.8'

services:
  adb-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adb-client
    environment:
      - ANDROID_ADB_SERVER_PORT=5037
      - ANDROID_ADB_SERVER_HOST=host.docker.internal
      - ANDROID_ADB_SERVER_ADDRESS=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/notorious/Dev/bot_inst/gramaddict:/app/.


#
#    networks:
#      - adb-network

#  socat:
#    image: alpine/socat
#    container_name: socat
#    command: TCP-LISTEN:5037,fork TCP:[host.docker.internal]:8080
#    depends_on:
#      - adb-server
#    networks:
#      - adb-network
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#
#networks:
#  adb-network:
#    driver: bridge
#
